name: pasaraja_mobile
description: "e-commerce pasar wage"

publish_to: 'none' 

version: 1.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg:
  pinput: ^3.0.1
  equatable: ^2.0.5
  lottie: ^3.0.0
  provider: ^6.1.2
  get: ^4.6.6
  vibration: ^1.8.4
  cached_network_image: ^3.3.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.7
  firebase_messaging: ^14.7.17
  http: ^1.1.2
  dio: ^5.4.1
  jwt_decoder: ^2.0.1
  carousel_slider: ^4.2.1
  dart_jsonwebtoken: ^2.13.0
  flutter_session_jwt: ^0.0.6
  flutter_native_splash: ^2.2.4
  logger: ^2.0.2+1
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.2.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.0.8
  d_input: ^0.1.2
  d_method: ^0.2.4
  talker_dio_logger: ^4.0.3
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  persistent_bottom_nav_bar: any
  qr_code_scanner: ^1.0.1
  pretty_qr_code: ^3.3.0
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.6
  local_auth: ^2.1.3
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/
      - assets/raws/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
